### ISSUE TITLE
Боты не удаляются по истчении времени в модуле

### ISSUE THREAD

**Issue by ruPaladin** [iEzhuk/WMT_MapTools#101]
Боты удаляются только по времени окончания фризтайма (модуль Time).
Если в модуле Time установить время, через которое боты будут удалены, меньше времени фризтайма, то боты все равно удалятся только по окончании фризтайма.

Баг критичен в случае нечестной игры. Если начать стрелять за 1-2 секунды до окончания фризтайма, есть шанс, что бот будет убит до удаления. Предотвратить это можно было бы установкой времени удаления меньше времени фризтайма, но это не работает из-за бага.

P. S. Большое спасибо за разработку модулей WMT. Значительно экономят время и упрощают создание миссий!

**Comment by ruPaladin** [comment]
Возможно, проблема кроется в fn_InitModuleTime.sqf:
if (wmt_param_RemoveBots > 0 && wmt_param_PrepareTime == 0)
вместо
if (wmt_param_RemoveBots > 0 && wmt_param_PrepareTime >= 0)

**Comment by iEzhuk** [comment]
Удаления ботов по времени должно срабатывать только в случае отсутствия фризтайма. 

Теперь не должно быть возможности убить ботов непосредственно в момент окончания фризтайма.
