### ISSUE TITLE
Условие для выбора победителя по завершению по времени

### ISSUE THREAD

**Issue by iEzhuk** [iEzhuk/WMT_MapTools#103]

**Comment by Zealot111** [comment]
Скорее просто возможность не завершить миссию а вызвать определенный код по окончании времени - намного проще

**Comment by Zealot111** [comment]
Например, сделать что если код при завершении миссии указан, то завершать миссию не стандартным сообщением, а вызовом этого кода.

**Comment by iEzhuk** [comment]
При определении функции с именем WMT_fnc_chooseWinnerByTime, для выбора победившей стороны и сообщения при окончании выбора

Пример 
# init.sqf
WMT_fnc_chooseWinnerByTime = 
{
   // _this содержит значения из модуля
   _winner = _this select 0;
   _text = _this select 1;
   switch (true) do 
   {
      case (conditio1) : 
      {
         _winner = west;
         _text = "West wins"
      };
      case (conditio2) : 
      {
         _winner = east;
         _text = "East wins"
      };
   };
   [_winner, _text]
};
